#!/usr/bin/env python3
"""One-shot: vendor SW classify → Git ``stock_sw_l2.yaml`` (§4 codes only)."""
from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Iterable, Optional

import yaml

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from scripts.common.universe import load_l2_to_l1, section4_codes

_TS_OK = re.compile(r"^\d{6}\.(SH|SZ)$")
_DEFAULT_OUT = os.path.join(_ROOT, "config", "taxonomy", "stock_sw_l2.yaml")


def _l2_name_to_code() -> dict[str, str]:
    return {r["name_zh"]: r["code"] for r in load_l2_to_l1() if r.get("name_zh")}


def _parent_l2(code: str, allowed: set[str]) -> Optional[str]:
    if not code or not str(code).isdigit():
        return None
    c = str(code)
    if c in allowed:
        return c
    if len(c) == 6:
        parent = c[:4] + "00"
        if parent in allowed:
            return parent
    return None


def normalize_member(
    ts_code: str,
    industry_code: str,
    industry_name: str = "",
    *,
    allowed: Optional[set[str]] = None,
    names: Optional[dict] = None,
) -> Optional[dict]:
    """Map one vendor row. ``None`` = drop (BJ / non-SH|SZ). Never emit 801xxx."""
    ts = (ts_code or "").strip().upper()
    if not _TS_OK.match(ts):
        return None
    allowed = allowed if allowed is not None else section4_codes()
    names = names if names is not None else _l2_name_to_code()
    raw = str(industry_code or "").strip()
    mapped = _parent_l2(raw, allowed)
    if mapped is None and industry_name:
        mapped = names.get(str(industry_name).strip())
    if mapped and mapped.startswith("801"):
        mapped = None
    return {"ts_code": ts, "sw_l2_code": mapped}


def _fmt_name_zh(name: str) -> str:
    if any(ch in name for ch in (":", "#", "{", "}", "[", "]", ",", '"', "'", "\\")):
        return yaml.dump(name, allow_unicode=True, default_style='"').strip()
    return name


def dump_yaml(
    vendor_rows: Iterable[dict],
    *,
    map_version: str = "sw2021-v1",
    prior_names: Optional[dict[str, str]] = None,
    allowed: Optional[set[str]] = None,
) -> str:
    allowed_set = allowed if allowed is not None else section4_codes()
    l2_names = _l2_name_to_code()
    prior = prior_names or {}
    members = []
    for row in vendor_rows:
        norm = normalize_member(
            row.get("ts_code") or "",
            str(row.get("industry_code") or ""),
            str(row.get("industry_name") or ""),
            allowed=allowed_set,
            names=l2_names,
        )
        if norm is None:
            continue
        members.append(norm)
    members.sort(key=lambda m: m["ts_code"])
    lines = [
        "map_version: %s" % map_version,
        "note: >",
        "  Generated by scripts/taxonomy/fetch_sw_members.py (SW classify snapshot).",
        "  sw_l2_code is taxonomy §4 only; null = quarantine. Never 801xxx.",
        "members:",
    ]
    if not members:
        lines.append("  []")
    for m in members:
        code = m["sw_l2_code"]
        code_s = "null" if not code else "'%s'" % code
        name = prior.get(m["ts_code"])
        if name not in (None, ""):
            lines.append(
                "  - {ts_code: %s, sw_l2_code: %s, name_zh: %s}"
                % (m["ts_code"], code_s, _fmt_name_zh(str(name)))
            )
        else:
            lines.append("  - {ts_code: %s, sw_l2_code: %s}" % (m["ts_code"], code_s))
    return "\n".join(lines) + "\n"


def _symbol_to_ts(symbol: str) -> Optional[str]:
    s = str(symbol).strip()
    if not re.match(r"^\d{6}$", s):
        return None
    if s.startswith(("4", "8", "9")):
        return None
    if s.startswith(("5", "6")):
        return s + ".SH"
    return s + ".SZ"


def fetch_latest_rows():
    import akshare as ak

    df = ak.stock_industry_clf_hist_sw()
    df = df.sort_values("start_date")
    latest = df.groupby("symbol", as_index=False).tail(1)
    rows = []
    for _, rec in latest.iterrows():
        ts = _symbol_to_ts(rec["symbol"])
        if ts is None:
            continue
        rows.append(
            {
                "ts_code": ts,
                "industry_code": rec["industry_code"],
                "industry_name": "",
            }
        )
    return rows


def _read_map_version_header(path: str) -> Optional[str]:
    """Return existing map_version from YAML header, or None if missing/unreadable."""
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                m = re.match(r"^map_version:\s*(\S+)\s*$", line)
                if m:
                    return m.group(1)
                if line.strip() and not line.startswith("#"):
                    break
    except OSError:
        return None
    return None


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", default=_DEFAULT_OUT)
    p.add_argument(
        "--map-version",
        default=None,
        help="map_version to write (default: keep existing header, else sw2021-v1)",
    )
    args = p.parse_args(argv)
    version = args.map_version or _read_map_version_header(args.out) or "sw2021-v1"
    text = dump_yaml(fetch_latest_rows(), map_version=version)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    print("[fetch_sw] wrote %s bytes=%d map_version=%s" % (args.out, len(text), version))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
